name: firebase_ml_labeling
description: A Flutter app for image labeling using Firebase ML Kit.

publish_to: 'none' # Remove this line if you plan to publish the package.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_image_labeling: ^0.4.0
  image_picker: ^0.8.7+3
  firebase_core: ^2.0.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
